[build]
  command = "npm install && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_BUILD_CACHE_DISABLED = "true"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/functions/next_image"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/next_data"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_handler"
  status = 200
